added sanity check for toolchain selection
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-0.10-trunk@5046 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -568,11 +568,21 @@ while [ "$#" != "0" ]; do
 	toolchain)	shift
 			echo
 			if [ ! -d "$1" ]; then
+				echo
 				echo "${PROMPT}error: path $1 does not exist"
 				echo
 				exit 1
 			fi
 			echo "${PROMPT}using toolchain in $1"
+			test -h ".toolchain" && rm -f .toolchain
+			if [ -e ".toolchain" ]; then
+				echo
+				echo "${PROMPT}error: There is a .toolchain in this directory which is no link."
+				echo "${PROMPT}error: This should never happen, please contact the"
+				echo "${PROMPT}error: Pengutronix Department of Illegal File Removement."
+				echo
+				exit 1
+			fi
 			ln -sf $1 .toolchain
 			echo
 			exit 0
