check if select target exists
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-0.10-trunk@5108 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -639,6 +639,12 @@ while [ "$#" != "0" ]; do
 
 	projects)	shift; projects;;
 	select)		shift
+			if [ ! -f "$1" ]; then
+				echo
+				echo "${PROMPT}error: couldn't select \"$1\", file does not exist"
+				echo
+				exit 1
+			fi
 			if [ -f "ptxconfig" ]; then
 				echo
 				echo "${PROMPT}error: There already is a ptxconfig file."
