* bin/ptxdist: 	only complain if there is really an error (where's my brown paper bag)
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@9751 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -1169,11 +1169,14 @@ do_config()
 		;;
 	esac
 
-	echo
-	echo "${PROMPT}'${part} ${config}' returned with an error"
-	echo
-	if [ $retval -ne 0 -a -n "${PTX_MENU}" ]; then
-		read
+	local retval=$?
+	if [ $retval -ne 0 ]; then
+		echo
+		echo "${PROMPT}'${part} ${config}' returned with an error"
+		echo
+		if [ -n "${PTX_MENU}" ]; then
+			read
+		fi
 	fi
 
 	return $retval
