ptxdist: fix newpacket sanity check
The sanity check for 'ptxdist newpacket' was recently changed to work
from a workspace; fix it to also work from a ptxdist toplevel directory.
In contrast to the old implementation, don't run this command from a
rules/ directory any more.

Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>

git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@10731 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -1807,14 +1807,13 @@ parse_second()
 			;;
 
 		newpacket)
-			check_config || return
-#			# test if we are in a rules dir
-#			if [ "$(basename $(pwd))" != "rules" ]; then
-#				echo
-#				echo "${PROMPT}error: newpacket command only allowed in a rules dir"
-#				echo
-#				exit 1
-#			fi
+			if [ \! -d "rules" ]; then
+				echo
+				echo "${PROMPT}error: no rules/ directory found"
+				echo "${PROMPT}error: please call from a workspace or ptxdist directory"
+				echo
+				exit 1
+			fi
 			newpacket "${1}"
 			exit
 			;;
