* allow both 'ptxdist drop sample compile' and 'ptxdist drop sample compile'
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-0.10-trunk@5609 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -337,6 +337,27 @@ clean() {
 	echo
 }
 
+drop() {
+	local statefile
+	if [ "$2" = "" ]; then
+		statefile="$1"
+	else
+		statefile="$1.$2"
+	fi
+
+	echo
+	if [ -e ${STATEDIR}/${statefile} ]; then
+		rm -f ${STATEDIR}/${statefile}
+		echo "droping ${statefile}"
+		echo
+		exit 0
+	else
+		echo "stage ${statefile} isn't built, so we cannot drop it"
+		echo
+		exit 1
+	fi
+}
+
 menuconfig() {
 	echo
 
@@ -680,17 +701,7 @@ while [ "$#" != "0" ]; do
 			;;
 	drop)		shift
 			check_ptxconfig
-			echo
-			if [ -e ${STATEDIR}/$1 ]; then
-				rm -f ${STATEDIR}/$1
-				echo "droping $1"
-				echo
-				exit 0
-			else
-				echo "stage $1 isn't built, so we cannot drop it"
-				echo
-				exit 1
-			fi
+			drop $1 $2
 			;;
 	extract)	shift
 			check_ptxconfig
