* export_src: rename 'export' to 'export_src', add errorchecks and help description
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@9119 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -605,9 +605,7 @@ Overwrite:
 Misc:
 
   --version			print out ptxdist version
-
   test <testname>		run tests
-
   newpacket <type>		create a new packet Makefile in a rules dir
 				<type> can be one of:
 				target, host, host-existing-target,
@@ -615,6 +613,9 @@ Misc:
 				kernel_driver, font, simple
   print <var>			print the contents of a variable, in the way
 				it is known by "make"
+  export_src <target dir>	export all source archives needed for this
+				project to <target dir>
+
 Options:
 
   -d				print out make decisions (debug)
@@ -1367,7 +1368,13 @@ parse_second()
 			drop "${1}" "${2}"
 			exit 0
 			;;
-		export)
+		export_src)
+			if [ -z "${1}" ]; then
+				echo
+				echo "${PROMPT}error: Please specify a target directory."
+				echo
+				exit 1
+			fi
 			if [ ! -d "${1}" ]; then
 				echo
 				echo "${PROMPT}error: directory '$1' does not exist!"
@@ -1376,7 +1383,7 @@ parse_second()
 			fi
 			check_ptxconfig || return
 			check_deps
-			ptxd_make_log export EXPORTDIR="${1}"
+			ptxd_make_log export_src EXPORTDIR="${1}"
 			exit 0
 			;;
 		get)
