* ptxdist: test if ptxdist projects do really exist before 	  doing something with them.
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@6878 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -664,6 +664,12 @@ projects() {
 	projects=
 	for projectdir in ${PTXCONF_SETUP_PROJECTPATH}; do
 		echo "${PROMPT}scanning ${projectdir}..."
+		if [ ! -d ${projectdir} ]; then
+			echo
+			echo "${PROMPT}error: directory does not exist"
+			echo "${PROMPT}please check PTXCONF_SETUP_PROJECTPATH in 'ptxdist setup'"
+			exit 1
+		fi
 		projects="$projects $(cd ${projectdir} && find .  -maxdepth 1 -type d ! -name .svn ! -name . -exec basename {} \;)"
 	done
 	IFS=$ifs_old
