[ptxdist] don't fail if config files don't define certain symbols
This patch fixes the commit

git: 0f0daf95ab605fe17d02d8daf214abf467d42549
svn: 10807

wich introduced a bug, so that projects with one of these symbols
("PTXCONF_PLATFORM, PTXCONF_PROJECT, PTXCONF_PROJECT_VERSION") missing
cannot be build.

Reported-by: Erwin Rol <erwin@erwinrol.com>
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>

git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@10811 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -2164,9 +2164,10 @@ setup_config() {
 setup_platform() {
 	local platform project project_version
 
-	platform="$(ptxd_get_ptxconf PTXCONF_PLATFORM)" &&
-	project="$(ptxd_get_ptxconf PTXCONF_PROJECT)" &&
-	project_version="$(ptxd_get_ptxconf PTXCONF_PROJECT_VERSION)" || return
+	# ptxd_get_ptxconf's return value is
+	platform="$(ptxd_get_ptxconf PTXCONF_PLATFORM)" || [ ${?} -eq 1 ] &&
+	project="$(ptxd_get_ptxconf PTXCONF_PROJECT)" || [ ${?} -eq 1 ] &&
+	project_version="$(ptxd_get_ptxconf PTXCONF_PROJECT_VERSION)" || [ ${?} -eq 1 ] || return
 
 	if [ -n "${platform}" ]; then
 		PTXDIST_PLATFORMDIR="${PTXDIST_WORKSPACE}/platform-${platform}"
