* bin/ptxdist: 	check for spaces in path names
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@8474 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -280,7 +280,20 @@ check_dirs_prefix() {
 	prefix="${1}"
 
 	if [ -z "${prefix}" ]; then
-		return
+		echo
+		echo
+		echo "${PROMPT}check_dirs_prefix(): error prefix is not defined"
+		echo
+		echo
+		exit 1
+	fi
+
+	if [ -n "${prefix#* }" ]; then
+		echo
+		echo "error: some important dir (\"${prefix}\")"
+		echo "contains spaces, this will probably not work, sorry"
+		echo
+		exit 1
 	fi
 
 	if [ ! -d "${prefix}" ]; then
