* platformconfig: add 'platform' command
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@7747 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -1115,6 +1115,30 @@ while [ "$#" != "0" ]; do
 			fi
 			exit $?
 			;;
+	platform)	shift
+			if [ ! -f "$1" ]; then
+				echo
+				echo "${PROMPT}error: couldn't select \"$1\", file does not exist"
+				echo
+				exit 1
+			fi
+			if [ -f "platformconfig" ]; then
+				echo
+				echo -n "${PROMPT}warning: overwrite existing platformconfig [y/n]? "
+				read answer
+				if [ "$answer" != "y" ]; then
+					echo "interrupting"
+					echo
+					exit 1
+				fi
+			fi
+			echo
+			echo "${PROMPT}selecting platformconfig \"$1\""
+			ln -sf $1 platformconfig
+			echo "${PROMPT}done."
+			echo
+			exit 0
+			;;
 	platformconfig)	shift
 			platformconfig
 			;;
