Rework template generation
Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>

git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@10657 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -936,13 +936,34 @@ drop() {
 	fi
 }
 
-
 newpacket() {
-	local packet_name version url author year suffix overwrite \
-	    template template_file template_suffix packet_filename packet_name packet PACKET packetdash filename \
-	    class CLASS autoconf_class
+	local \
+		packet_name \
+		version \
+		url \
+		author \
+		year \
+		suffix \
+		overwrite \
+		template \
+		template_file \
+		template_suffix \
+		template_src \
+		packet_filename \
+		packet_name \
+		packet \
+		PACKET \
+		packetdash \
+		filename \
+		class \
+		CLASS \
+		autoconf_class \
+		action \
+		exists
 
-	case "$1" in
+	action=$1
+
+	case "$action" in
 	target)
 		template=template
 		class=
@@ -958,18 +979,21 @@ newpacket() {
 		class=cross-
 		autoconf_class=HOST_CROSS_
 		;;
-	host-existing-target)
-		template=template-class-existing-target
-		class=host-
-		autoconf_class=HOST_
+	src-autoconf-prog)
+		template=template-src-autoconf
+		template_src="${PTXDIST_TOPDIR}/rules/templates/src-autoconf-prog"
+		class=
+		autoconf_class=
 		;;
-	cross-existing-target)
-		template=template-class-existing-target
-		class=cross-
-		autoconf_class=HOST_CROSS_
+	src-autoconf-lib)
+		template=template-src-autoconf
+		template_src="${PTXDIST_TOPDIR}/rules/templates/src-autoconf-lib"
+		class=
+		autoconf_class=
 		;;
-	source)
-		template=template-src
+	src-autoconf-proglib)
+		template=template-src-autoconf
+		template_src="${PTXDIST_TOPDIR}/rules/templates/src-autoconf-proglib"
 		class=
 		autoconf_class=
 		;;
@@ -990,27 +1014,81 @@ newpacket() {
 		;;
 	*)
 		echo
-		echo "${PROMPT}error: illegal packet type: $1"
-		echo "must be one of host, host-existing-target, target,"
-		echo "cross, cross-existing-target, source, kernel_driver, font, simple"
+		echo "usage: 'ptxdist newpacket <class>', where class is:"
+		echo
+		echo "  host                     create package for development host"
+		echo "  target                   create package for embedded target"
+		echo "  cross                    create cross development package"
+		echo
+		echo "  src-autoconf-prog        create autotoolized binary"
+		echo "  src-autoconf-lib         create autotoolized library"
+		echo "  src-autoconf-proglib     create autotoolized binary+library"
+		echo "  src-plain-make           create binary with plain makefile"
+		echo "  kernel_driver            "
+		echo "  font"
+		echo "  simple"
 		echo
 		exit 1
 		;;
 	esac
 
+	#
+	# Ask some questions
+	#
+
 	echo
-	echo "${PROMPT}creating a new packet:"
+	echo "${PROMPT}creating a new \"${action}\" package:"
 	echo
 	echo -n "${PROMPT}enter packet name.......: "
 	read packet_name
-	echo -n "${PROMPT}enter version number....: "
-	read version
-	echo -n "${PROMPT}enter URL of basedir....: "
-	read url
+
+	#
+	# for host and cross packages, find out if there is already an
+	# existing target
+	#
+
+	exists=
+	[ -f "${PTXDIST_WORKSPACE}/rules/${packet_name}.make" ] && exists=1
+	[ -f "${PTXDIST_TOPDIR}/rules/${packet_name}.make" ] && exists=1
+
+	if [ "$action" = "host" ]  && [ -n $exists ]; then
+		action=host-existing-target
+		template=template-class-existing-target
+		class=host-
+		autoconf_class=HOST_
+	fi
+	if [ "$action" = "cross" ] && [ -n $exists ]; then
+		action=cross-existing-target
+		template=template-class-existing-target
+		class=cross-
+		autoconf_class=HOST_CROSS_
+	fi
+
+	#
+	# more questions ...
+	#
+
+	case "$action" in
+	host-existing-target|cross-existing-target)
+		;;
+	*)
+		echo -n "${PROMPT}enter version number....: "
+		read version
+		;;
+	esac
+
+	case "$action" in
+	host,target,cross)
+		echo -n "${PROMPT}enter URL of basedir....: "
+		read url
+		echo -n "${PROMPT}enter suffix............: "
+		read suffix
+		;;
+	esac
+
+	# FIXME: guess automatically
 	echo -n "${PROMPT}enter packet author.....: "
 	read author
-	echo -n "${PROMPT}enter suffix............: "
-	read suffix
 
 	packet_filename="${packet_name}"
 
@@ -1022,8 +1100,9 @@ newpacket() {
 	year="$(date +%Y)"
 
 	for template_suffix in "make" "in"; do
+
 		template_file="${TEMPLATESDIR}/${template}-${template_suffix}"
-		filename="${class}${packet_filename}.${template_suffix}"
+		filename="${PTXDIST_WORKSPACE}/rules/${class}${packet_filename}.${template_suffix}"
 
 		if [ ! -f "${template_file}" ]; then
 			echo
@@ -1059,6 +1138,24 @@ newpacket() {
 		"${template_file}" \
 		> "${filename}"
 	done
+
+	#
+	# for local src-* packages, check if we have to create a template
+	#
+
+	case "$action" in
+	src-*)
+		[ -d "${PTXDIST_WORKSPACE}/local_src/${packet}-${version}" ] && return
+		echo -e -n "\nlocal_src/${packet}-${version} does not exist, create? [y/n] "
+		[ "$(local r; read r; echo $r)" = "y" ] || return
+		mkdir -p "${PTXDIST_WORKSPACE}/local_src/${packet}-${version}"
+		tar -C "${template_src}" -cf - --exclude .svn . | \
+			tar -C "${PTXDIST_WORKSPACE}/local_src/${packet}-${version}" -xvf -
+		(cd "${PTXDIST_WORKSPACE}/local_src/${packet}-${version}" && sh wizzard.sh ${packet})
+		rm -f ${PTXDIST_WORKSPACE}/local_src/${packet}-${version}/wizzard.sh
+		;;
+	esac
+
 }
 
 
@@ -1712,13 +1809,14 @@ parse_second()
 			;;
 
 		newpacket)
-			# test if we are in a rules dir
-			if [ "$(basename $(pwd))" != "rules" ]; then
-				echo
-				echo "${PROMPT}error: newpacket command only allowed in a rules dir"
-				echo
-				exit 1
-			fi
+			check_config || return
+#			# test if we are in a rules dir
+#			if [ "$(basename $(pwd))" != "rules" ]; then
+#				echo
+#				echo "${PROMPT}error: newpacket command only allowed in a rules dir"
+#				echo
+#				exit 1
+#			fi
 			newpacket "${1}"
 			exit ${?}
 			;;
