* ptxdist: added 'ptxdist maintainer configversionbump' 	* ptxdist: copy with tar instead of cp, to exclude svn
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-0.10-trunk@5185 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -494,18 +494,36 @@ clone() {
 	for i in $projects; do
 		if [ "$1" = "$i" ]; then
 			echo "${PROMPT}cloning project $1 to $2"
+
 			if [ -d "${PTXCONF_SETUP_PROJECTDIR}" ] && [ -d "${PTXCONF_SETUP_PROJECTDIR}/$1" ] ; then
-				cp -a ${PTXCONF_SETUP_PROJECTDIR}/$1 $2
+
+				mkdir -p $2
+				tar -C ${PTXCONF_SETUP_PROJECTDIR}/$1 -cf - \
+				    --exclude .svn --exclude state --exclude debian . | \
+				    tar -C $2 -xvf -
+
 				echo "${PROMPT}done."
 				echo
 				return 0
+
 			elif [ -d "${PTXDIST_TOPDIR}/projects-example/$1" ]; then
-				cp -a ${PTXDIST_TOPDIR}/projects-example/$1 $2
+
+				mkdir -p $2
+				tar -C ${PTXDIST_TOPDIR}/projects-example/$1 -cf - \
+				    --exclude .svn --exclude state --exclude debian . | \
+				    tar -C $2 -xvf -
+
 				echo "${PROMPT}done."
 				echo
 				return 0
+
 			elif [ -d "${PTXDIST_TOPDIR}/projects-toolchains/$1" ]; then
-				cp -a ${PTXDIST_TOPDIR}/projects-toolchains/$1 $2
+
+				mkdir -p $2
+				tar -C ${PTXDIST_TOPDIR}/projects-toolchains/$1 -cf - \
+				    --exclude .svn --exclude state --exclude debian . | \
+				    tar -C $2 -xvf -
+
 				echo "${PROMPT}done."
 				echo
 				return 0
@@ -657,6 +675,36 @@ while [ "$#" != "0" ]; do
 			check_ptxconfig
 			check_kernelconfig
 			kernelconfig
+			;;
+	maintainer)	shift
+			if [ "$#" = "0" ]; then
+				echo
+				echo "${PROMPT} commands:"
+				echo
+				echo "${PROMPT} configversionbump"
+				echo
+				exit 0
+			fi
+			case $1 in
+			configversionbump)
+				echo
+				echo "${PROMPT} configversionbump:"
+				echo
+				for i in $(find . -name "ptxconfig*"); do
+					echo "${PROMPT} version fixup in $i..."
+					sed -i -e \
+						"s/PTXCONF_CONFIGFILE_VERSION=\".*\"/PTXCONF_CONFIGFILE_VERSION=\"${FULLVERSION}\"/g" \
+						$i
+				done
+				;;
+			*)
+				echo
+				echo "${PROMPT} error: unknown command: $1"
+				echo
+				exit 1
+				;;
+			esac
+			exit 0
 			;;
 	make)		shift
 			check_ptxconfig
