* ptxdist: 	put second stage parse into own function
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@8554 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/bin/ptxdist b/bin/ptxdist
--- a/bin/ptxdist
+++ b/bin/ptxdist
@@ -999,8 +999,9 @@ toolchain() {
 
 
 
-
+##################################################################
 ################ "minusminus" option parser ######################
+##################################################################
 
 parse_first()
 {
@@ -1050,7 +1051,360 @@ parse_first()
 }
 
 
+
+##################################################################
+################ normal option parser ############################
+##################################################################
+
+parse_second()
+{
+	#
+	# use args from first stage parser, prepared for us
+	#
+	set --  "${PTXDIST_ARGS_SECOND[@]}"
+	
+	if [ $# -eq 0 ]; then
+		usage
+		exit 0
+	fi
+	
+	while [ $# -ne 0 ]; do
+		local ptx_cmd="${1}"
+		shift
+	
+		case "${ptx_cmd}" in
+		--version)
+			echo "${FULLVERSION}"
+			exit 0
+			;;
+	
+		--help|help)
+			usage
+			exit 0
+			;;
+	
+		extract|prepare|compile|install|targetinstall|tags)
+			if [ "${ptx_cmd}" = "targetinstall" ]; then
+				ptx_cmd_post=".post"
+			fi
+			check_ptxconfig
+			check_if_selected "${1}"
+			check_compiler
+			check_dirs
+			check_deps
+			ptxd_make_log "${STATEDIR}/${1}.${ptx_cmd}${ptx_cmd_post}"
+			exit 0
+			;;
+	
+		autobuild)
+			echo
+			echo "${PROMPT}running autobuild"
+			echo
+			AUTOBUILDS=$(find . -name "autobuild*" | grep -v .svn)
+			AUTOBUILD_TOPDIR=$(pwd)
+			exec 5>COMPILETEST
+			echo >&5
+			for i in $AUTOBUILDS; do
+				pushd $(dirname $i)
+
+				echo "config............: $(basename $(pwd))" >&5
+				echo "date..............: $(date)" >&5
+				echo "user..............: ${USER}@${HOSTNAME}" >&5
+				PTX_STARTTIME=$(date +"%s")
+
+				./$(basename $i)
+
+				PTX_RETVAL=$?
+				PTX_STOPTIME=$(date +"%s")
+				let "PTX_TIME=$PTX_STOPTIME-$PTX_STARTTIME"
+				let "PTX_TIME_H=$PTX_TIME/3600"
+				let "PTX_TIME_M=($PTX_TIME-$PTX_TIME_H*3600)/60"
+				let "PTX_TIME_S=($PTX_TIME-$PTX_TIME_H*3600-$PTX_TIME_M*60)/60"
+				echo "buildtime.........: ${PTX_TIME_H}h${PTX_TIME_M}m${PTX_TIME_S}s" >&5
+				echo "result............: ${PTX_RETVAL}" >&5
+				echo >&5
+
+				[ -e "logfile" ] && mv logfile "${AUTOBUILD_TOPDIR}/$(basename $(pwd)).log"
+				[ "${PTX_RETVAL}" = "0" ] && ${PTXDIST} distclean
+
+				popd
+			done
+			echo
+			echo "${PROMPT}done"
+			echo
+			exit 0
+			;;
+		boardsetup)
+			check_ptxconfig
+			boardsetup
+			exit 0
+			;;
+		clean)
+			check_ptxconfig
+			check_deps
+			clean "${1}"
+			exit 0
+				;;
+		clone)
+			if [ $# -ne 2 ]; then
+				usage
+				exit 1
+			fi
+
+			clone "${1}" "${2}"
+			exit 0
+			;;
+		distclean)
+			clean
+
+			if [ -L "${PTXDIST_TOOLCHAIN}" ]; then
+				echo "${PROMPT}removing toolchain link..."
+				rm -f "${PTXDIST_TOOLCHAIN}"
+			fi
+
+			if [ -L "${PTXDIST_PTXCONFIG}" ]; then
+				echo "${PROMPT}removing ptxconfig link..."
+				rm "${PTXDIST_PTXCONFIG}"
+	
+			fi
+			if [ -L "${PTXDIST_PLATFORMCONFIG}" ]; then
+				echo "${PROMPT}removing platformconfig link..."
+				rm "${PTXDIST_PLATFORMCONFIG}"
+			fi
+
+			echo "${PROMPT}removing logs..."
+			rm -fr "${PTXDIST_PLATFORMDIR}/logfile"
+
+			echo
+			exit 0
+			;;
+		drop)
+			check_ptxconfig
+			drop "${1}" "${2}"
+			exit 0
+			;;
+		export)
+			if [ ! -d "${1}" ]; then
+				echo
+				echo "${PROMPT}error: directory '$1' does not exist!"
+				echo
+				exit 1
+			fi
+			check_ptxconfig
+			check_deps
+			ptxd_make_log export EXPORTDIR="${1}"
+			exit 0
+			;;
+		get)
+			check_ptxconfig
+			check_deps
+			if [ $# -eq 0 ]; then
+				ptxd_make_log get
+			else
+				check_if_selected "${1}"
+				ptxd_make_log "${STATEDIR}/${1}.get"
+			fi
+			exit 0
+			;;
+		go)
+			check_ptxconfig
+			check_compiler
+			check_dirs
+			check_deps
+			ptxd_make_log world
+			exit 0
+			;;
+		images)
+			check_ptxconfig
+			check_compiler
+			check_dirs
+			check_deps
+			ptxd_make_log world
+			ptxd_make_log images
+			exit 0
+			;;
+		kernelconfig)
+			check_ptxconfig
+			check_deps
+			ptxd_make kernel_menuconfig
+			exit 0
+			;;
+		u_boot_config)
+			check_ptxconfig
+			check_deps
+			ptxd_make u-boot-v2_menuconfig
+			exit 0
+			;;
+		make)
+			check_ptxconfig
+			check_compiler
+			check_dirs
+			check_deps
+			ptxd_make_log "${1}"
+			exit 0
+			;;
+		menu)
+			while menu; do true; done
+			exit 0
+			;;
+		menuconfig)
+			check_ptxconfig
+			case "${1}" in
+			    ""|"ptxdist")
+				ptxd_kconfig "${PTXDIST_PTXCONFIG}" menuconfig_action true
+				;;
+			    "platform")
+				ptxd_kconfig "${PTXDIST_PLATFORMCONFIG}" platform_config_action true
+				;;
+			    *)
+				check_if_selected "${1}"
+				check_deps
+				ptxd_make "${1}_menuconfig"
+			esac
+			exit ${?}
+			;;
+		newpacket)	# test if we are in a rules dir
+			if [ "$(basename $(pwd))" != "rules" ]; then
+				echo
+				echo "${PROMPT}error: newpacket command only allowed in a rules dir"
+				echo
+				exit 1
+			fi
+			newpacket "${1}"
+			exit $?
+			;;
+		oldconfig)
+			check_ptxconfig
+			case "${1}" in
+			    ""|"ptxdist")
+				ptxd_kconfig "${PTXDIST_PTXCONFIG}" oldconfig_action true
+				;;
+			    "platform")
+				ptxd_kconfig "${PTXDIST_PLATFORMCONFIG}" platform_oldconfig_action true
+				;;
+			    *)
+				check_if_selected "${1}"
+				check_deps
+				ptxd_make "${1}_oldconfig"
+			esac
+			exit ${?}
+			;;
+		platform)
+			check_nonstandard "platform"
+			if [ ! -f "${1}" ]; then
+				echo
+				echo "${PROMPT}error: couldn't select \"${1}\", file does not exist"
+				echo
+				exit 1
+			elif [ -f "${PTXDIST_PLATFORMCONFIG}" ]; then
+				echo
+				echo -n "${PROMPT}warning: overwrite existing platformconfig [Y/n]? "
+				read answer
+				if [ "${answer}" != "y" -a "${answer}" != "" ]; then
+					echo "interrupting"
+					echo
+					exit 1
+				fi
+			fi
+			echo
+			echo "${PROMPT}selecting platformconfig \"${1}\""
+			ln -sf "${1}" "${PTXDIST_PLATFORMCONFIG}"
+			echo "${PROMPT}done."
+			echo
+			exit 0
+			;;
+		platformconfig)
+			ptxd_kconfig "${PTXDIST_PLATFORMCONFIG}" platform_config_action true
+			exit 0
+				;;
+		print)
+			check_ptxconfig
+			check_deps
+			ptxd_make_log "print-${1}"
+			shift
+			;;
+		projects)
+			projects
+			exit 0
+			;;
+		select)
+			check_nonstandard "ptxconfig"
+
+			if [ ! -f "${1}" ]; then
+				echo
+				echo "${PROMPT}error: couldn't select \"${1}\", file does not exist"
+				echo
+				exit 1
+			fi
+			if [ -f "${PTXDIST_PTXCONFIG}" -a ! -L "${PTXDIST_PTXCONFIG}" ]; then
+				echo
+				echo "${PROMPT}error: There already is a ptxconfig file."
+				echo "${PROMPT}error: If you really want to select another configuration,"
+				echo "${PROMPT}error: please move away the ptxconfig file first."
+				echo
+				exit 1
+			fi
+			echo
+			echo "${PROMPT}linking $1 to ptxconfig"
+			ln -sf "${1}" "${PTXDIST_PTXCONFIG}"
+			echo "${PROMPT}done."
+			echo
+			exit 0
+			;;
+		setup)
+			ptxd_kconfig "${PTXDISTRC}" setup_action true
+			exit 0
+				;;
+		test)
+			if [ -z "$1" ]; then
+				echo "No test given. try ptxdist test help for a list of available tests"
+				exit 1
+			fi
+			if [ "$1" = help ]; then
+				# FIXME
+				echo "available tests:"
+				find $PTXDIST_WORKSPACE/tests -maxdepth 1 -type f -exec basename {} \;
+				exit 0
+			fi
+
+			for tst in \
+				"${PTXDIST_PLATFORMCONFIGDIR}/tests/${1}${PTXDIST_PLATFORMSUFFIX}" \
+				"${PTXDIST_PLATFORMCONFIGDIR}/tests/${1}" \
+				"${PTXDIST_WORKSPACE}/tests/${1}${PTXDIST_PLATFORMSUFFIX}" \
+				"${PTXDIST_WORKSPACE}/tests/${1}" \
+				"${PTXDIST_TOPDIR}/tests/${1}${PTXDIST_PLATFORMSUFFIX}" \
+				"${PTXDIST_TOPDIR}/tests/${1}" \
+				; do \
+				if [ -x "${tst}" ]; then
+					"${tst}" > "${PTXDIST_PLATFORMDIR}/test.log"
+					exit $?
+				fi
+			done
+
+			echo
+			echo "${PROMPT}error: test '$1' not found in PTXDIST_TOPDIR and PTXDIST_WORKSPACE"
+			echo
+			exit 1
+			;;
+		toolchain)
+			check_nonstandard "toolchain"
+			toolchain "${1}"
+			exit 0
+			;;
+		*)
+			usage
+			exit 1
+			;;
+		esac
+
+	done
+}
+
+
+
+##################################################################
 ################ setup stuff only ################################
+##################################################################
 
 
 #
@@ -1349,345 +1703,6 @@ export \
 check_uid
 check_path
 
-#
-# use args from first stage parser, prepared for us
-#
-set --  "${PTXDIST_ARGS_SECOND[@]}"
+parse_second
 
-if [ $# -eq 0 ]; then
-	usage
-	exit 0
-fi
-
-while [ $# -ne 0 ]; do
-	ptx_cmd="${1}"
-	shift
-
-	case "${ptx_cmd}" in
-	--version)
-			echo "${FULLVERSION}"
-			exit 0
-			;;
-
-	--help|help)
-			usage
-			exit 0
-			;;
-
-	extract|prepare|compile|install|targetinstall|tags)
-			if [ "${ptx_cmd}" = "targetinstall" ]; then
-				ptx_cmd_post=".post"
-			fi
-			check_ptxconfig
-			check_if_selected "${1}"
-			check_compiler
-			check_dirs
-			check_deps
-			ptxd_make_log "${STATEDIR}/${1}.${ptx_cmd}${ptx_cmd_post}"
-			exit 0
-			;;
-
-	autobuild)
-			echo
-			echo "${PROMPT}running autobuild"
-			echo
-			AUTOBUILDS=$(find . -name "autobuild*" | grep -v .svn)
-			AUTOBUILD_TOPDIR=$(pwd)
-			exec 5>COMPILETEST
-			echo >&5
-			for i in $AUTOBUILDS; do
-				pushd $(dirname $i)
-
-				echo "config............: $(basename $(pwd))" >&5
-				echo "date..............: $(date)" >&5
-				echo "user..............: ${USER}@${HOSTNAME}" >&5
-				PTX_STARTTIME=$(date +"%s")
-
-				./$(basename $i)
-
-				PTX_RETVAL=$?
-				PTX_STOPTIME=$(date +"%s")
-				let "PTX_TIME=$PTX_STOPTIME-$PTX_STARTTIME"
-				let "PTX_TIME_H=$PTX_TIME/3600"
-				let "PTX_TIME_M=($PTX_TIME-$PTX_TIME_H*3600)/60"
-				let "PTX_TIME_S=($PTX_TIME-$PTX_TIME_H*3600-$PTX_TIME_M*60)/60"
-				echo "buildtime.........: ${PTX_TIME_H}h${PTX_TIME_M}m${PTX_TIME_S}s" >&5
-				echo "result............: ${PTX_RETVAL}" >&5
-				echo >&5
-
-				[ -e "logfile" ] && mv logfile "${AUTOBUILD_TOPDIR}/$(basename $(pwd)).log"
-				[ "${PTX_RETVAL}" = "0" ] && ${PTXDIST} distclean
-
-				popd
-			done
-			echo
-			echo "${PROMPT}done"
-			echo
-			exit 0
-			;;
-	boardsetup)
-			check_ptxconfig
-			boardsetup
-			exit 0
-			;;
-	clean)
-			check_ptxconfig
-			check_deps
-			clean "${1}"
-			exit 0
-			;;
-	clone)
-			if [ $# -ne 2 ]; then
-				usage
-				exit 1
-			fi
-
-			clone "${1}" "${2}"
-			exit 0
-			;;
-	distclean)
-			clean
-
-			if [ -L "${PTXDIST_TOOLCHAIN}" ]; then
-				echo "${PROMPT}removing toolchain link..."
-				rm -f "${PTXDIST_TOOLCHAIN}"
-			fi
-
-			if [ -L "${PTXDIST_PTXCONFIG}" ]; then
-				echo "${PROMPT}removing ptxconfig link..."
-				rm "${PTXDIST_PTXCONFIG}"
-
-			fi
-			if [ -L "${PTXDIST_PLATFORMCONFIG}" ]; then
-				echo "${PROMPT}removing platformconfig link..."
-				rm "${PTXDIST_PLATFORMCONFIG}"
-			fi
-
-			echo "${PROMPT}removing logs..."
-			rm -fr "${PTXDIST_PLATFORMDIR}/logfile"
-
-			echo
-			exit 0
-			;;
-	drop)
-			check_ptxconfig
-			drop "${1}" "${2}"
-			exit 0
-			;;
-	export)
-			if [ ! -d "${1}" ]; then
-				echo
-				echo "${PROMPT}error: directory '$1' does not exist!"
-				echo
-				exit 1
-			fi
-			check_ptxconfig
-			check_deps
-			ptxd_make_log export EXPORTDIR="${1}"
-			exit 0
-			;;
-	get)
-			check_ptxconfig
-			check_deps
-			if [ $# -eq 0 ]; then
-				ptxd_make_log get
-			else
-				check_if_selected "${1}"
-				ptxd_make_log "${STATEDIR}/${1}.get"
-			fi
-			exit 0
-			;;
-	go)
-			check_ptxconfig
-			check_compiler
-			check_dirs
-			check_deps
-			ptxd_make_log world
-			exit 0
-			;;
-	images)
-			check_ptxconfig
-			check_compiler
-			check_dirs
-			check_deps
-			ptxd_make_log world
-			ptxd_make_log images
-			exit 0
-			;;
-	kernelconfig)
-			check_ptxconfig
-			check_deps
-			ptxd_make kernel_menuconfig
-			exit 0
-			;;
-	u_boot_config)
-			check_ptxconfig
-			check_deps
-			ptxd_make u-boot-v2_menuconfig
-			exit 0
-			;;
-	make)
-			check_ptxconfig
-			check_compiler
-			check_dirs
-			check_deps
-			ptxd_make_log "${1}"
-			exit 0
-			;;
-	menu)
-			while menu; do true; done
-			exit 0
-			;;
-	menuconfig)
-			check_ptxconfig
-			case "${1}" in
-			    ""|"ptxdist")
-				ptxd_kconfig "${PTXDIST_PTXCONFIG}" menuconfig_action true
-				;;
-			    "platform")
-				ptxd_kconfig "${PTXDIST_PLATFORMCONFIG}" platform_config_action true
-				;;
-			    *)
-				check_if_selected "${1}"
-				check_deps
-				ptxd_make "${1}_menuconfig"
-			esac
-			exit ${?}
-			;;
-	newpacket)	# test if we are in a rules dir
-			if [ "$(basename $(pwd))" != "rules" ]; then
-				echo
-				echo "${PROMPT}error: newpacket command only allowed in a rules dir"
-				echo
-				exit 1
-			fi
-			newpacket "${1}"
-			exit $?
-			;;
-	oldconfig)
-			check_ptxconfig
-			case "${1}" in
-			    ""|"ptxdist")
-				ptxd_kconfig "${PTXDIST_PTXCONFIG}" oldconfig_action true
-				;;
-			    "platform")
-				ptxd_kconfig "${PTXDIST_PLATFORMCONFIG}" platform_oldconfig_action true
-				;;
-			    *)
-				check_if_selected "${1}"
-				check_deps
-				ptxd_make "${1}_oldconfig"
-			esac
-			exit ${?}
-			;;
-	platform)
-			check_nonstandard "platform"
-			if [ ! -f "${1}" ]; then
-				echo
-				echo "${PROMPT}error: couldn't select \"${1}\", file does not exist"
-				echo
-				exit 1
-			elif [ -f "${PTXDIST_PLATFORMCONFIG}" ]; then
-				echo
-				echo -n "${PROMPT}warning: overwrite existing platformconfig [Y/n]? "
-				read answer
-				if [ "${answer}" != "y" -a "${answer}" != "" ]; then
-					echo "interrupting"
-					echo
-					exit 1
-				fi
-			fi
-			echo
-			echo "${PROMPT}selecting platformconfig \"${1}\""
-			ln -sf "${1}" "${PTXDIST_PLATFORMCONFIG}"
-			echo "${PROMPT}done."
-			echo
-			exit 0
-			;;
-	platformconfig)
-			ptxd_kconfig "${PTXDIST_PLATFORMCONFIG}" platform_config_action true
-			exit 0
-			;;
-	print)
-			check_ptxconfig
-			check_deps
-			ptxd_make_log "print-${1}"
-			shift
-			;;
-	projects)
-			projects
-			exit 0
-			;;
-	select)
-			check_nonstandard "ptxconfig"
-
-			if [ ! -f "${1}" ]; then
-				echo
-				echo "${PROMPT}error: couldn't select \"${1}\", file does not exist"
-				echo
-				exit 1
-			fi
-			if [ -f "${PTXDIST_PTXCONFIG}" -a ! -L "${PTXDIST_PTXCONFIG}" ]; then
-				echo
-				echo "${PROMPT}error: There already is a ptxconfig file."
-				echo "${PROMPT}error: If you really want to select another configuration,"
-				echo "${PROMPT}error: please move away the ptxconfig file first."
-				echo
-				exit 1
-			fi
-			echo
-			echo "${PROMPT}linking $1 to ptxconfig"
-			ln -sf "${1}" "${PTXDIST_PTXCONFIG}"
-			echo "${PROMPT}done."
-			echo
-			exit 0
-			;;
-	setup)
-			ptxd_kconfig "${PTXDISTRC}" setup_action true
-			exit 0
-			;;
-	test)
-			if [ -z "$1" ]; then
-				echo "No test given. try ptxdist test help for a list of available tests"
-				exit 1
-			fi
-			if [ "$1" = help ]; then
-				# FIXME
-				echo "available tests:"
-				find $PTXDIST_WORKSPACE/tests -maxdepth 1 -type f -exec basename {} \;
-				exit 0
-			fi
-
-			for tst in \
-				"${PTXDIST_PLATFORMCONFIGDIR}/tests/${1}${PTXDIST_PLATFORMSUFFIX}" \
-				"${PTXDIST_PLATFORMCONFIGDIR}/tests/${1}" \
-				"${PTXDIST_WORKSPACE}/tests/${1}${PTXDIST_PLATFORMSUFFIX}" \
-				"${PTXDIST_WORKSPACE}/tests/${1}" \
-				"${PTXDIST_TOPDIR}/tests/${1}${PTXDIST_PLATFORMSUFFIX}" \
-				"${PTXDIST_TOPDIR}/tests/${1}" \
-				; do \
-				if [ -x "${tst}" ]; then
-					"${tst}" > "${PTXDIST_PLATFORMDIR}/test.log"
-					exit $?
-				fi
-			done
-
-			echo
-			echo "${PROMPT}error: test '$1' not found in PTXDIST_TOPDIR and PTXDIST_WORKSPACE"
-			echo
-			exit 1
-			;;
-	toolchain)
-			check_nonstandard "toolchain"
-			toolchain "${1}"
-			exit 0
-			;;
-	*)
-			usage
-			exit 1
-			;;
-	esac
-
-done
-
-exit 0
+exit 1
