fix FULLVERSION; add todos
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-0.10-trunk@4522 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,6 +5,19 @@
 #
 # - modify parser to understand --prefix=/foo, not only --prefix /foo
 #
+# - test for ncurses headers:
+# 
+#         @echo -e "#include \"ncurses.h\"\nint main(void){}" | gcc -E - > /dev/null;     \
+#         if [ "$$?" = "1" ]; then                                                        \
+#                 echo;                                                                   \
+#                 echo "Error: you don't seem to have ncurses.h; this probably means";    \
+#                 echo "       that you'll have to install some ncurses-devel packet";    \
+#                 echo "       from your distribution.";                                  \
+#                 echo;                                                                   \
+#                 exit 1;                                                                 \
+#         fi
+#
+
 
 PROMPT="ptxdist: "
 PTXDIST_TOPDIR=$(cd $(dirname $0) && pwd)
@@ -54,9 +67,9 @@ invoke_parser $@
 prefix=${PREFIX:="/usr/local"}
 libdir="${prefix}/lib"
 bindir="${prefix}/bin"
-instdir="${libdir}/ptxdist-${PTXDIST_FULLVERSION}"
+instdir="${libdir}/ptxdist-${FULLVERSION}"
 
-echo "checking version=${PTXDIST_FULLVERSION}"
+echo "checking version=${FULLVERSION}"
 echo "checking prefix=${prefix}"
 echo "checking topdir=${PTXDIST_TOPDIR}"
 echo "checking instdir=${instdir}"
@@ -67,6 +80,6 @@ cat "${PTXDIST_TOPDIR}/Makefile.in" | \
 	sed -e "s,@PREFIX@,\"${prefix}\",g" | \
 	sed -e "s,@TOPDIR@,\"${PTXDIST_TOPDIR}\",g" | \
 	sed -e "s,@INSTDIR@,\"${instdir}\",g" | \
-	sed -e "s,@VERSION@,\"${PTXDIST_FULLVERSION}\",g" \
+	sed -e "s,@VERSION@,\"${FULLVERSION}\",g" \
 	> ${PTXDIST_TOPDIR}/Makefile
 
