Update
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunk@1176 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/etc/bmwm-cid_internet/init.d/ppp-daemon b/etc/bmwm-cid_internet/init.d/ppp-daemon
--- a/etc/bmwm-cid_internet/init.d/ppp-daemon
+++ b/etc/bmwm-cid_internet/init.d/ppp-daemon
@@ -17,7 +17,9 @@ case $1 in
 		echo "loading ppp daemon:"
 		/usr/sbin/pppd call gprs
 		sleep 1
+		echo "initially shuting down link"
 		ifconfig ppp0 down
+		[ "$?" ] || { echo "failed!"; exit -1; } 
 		echo "done."
 		;;
 	stop)
