make environment scripts standalone usable
Calling make_barebox_env and make_uboot_v2_env directly by "ptxdist test ..."
used to fail since these scripts depends on some preconditions set by "ptxdist
test setenv". Add fix so that these scripts can also be used directly.

Signed-off-by: Luotao Fu <l.fu@pengutronix.de>
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>

diff --git a/tests/make_barebox_env b/tests/make_barebox_env
--- a/tests/make_barebox_env
+++ b/tests/make_barebox_env
@@ -4,6 +4,15 @@ set -e
 PTXDIST_SETENV_BAREBOX_ENV="${1}"
 ENVTMPDIR="$(mktemp -d "${PTXDIST_TEMPDIR}/barebox_env.XXXXXX")"
 
+# IMAGEDIR is not set if we use this script with "ptxdist test" directly
+# since it comes from kwraper.
+[ -z "${IMAGEDIR}" ] && export IMAGEDIR=${PTXDIST_PLATFORMDIR}/images
+
+if [ ! -r ${PTXDIST_PLATFORMCONFIGDIR}/barebox-env/config ]; then
+	echo "ERROR: missing valid ${PTXDIST_PLATFORMCONFIGDIR}/barebox-env/config" >&2
+	exit 1
+fi
+
 tar -C "${PTXDIST_PLATFORMCONFIGDIR}/barebox-env/" -c . \
 	--exclude .svn \
 	--exclude .pc \
@@ -12,8 +21,9 @@ tar -C "${PTXDIST_PLATFORMCONFIGDIR}/barebox-env/" -c . \
 	--exclude "*/*~" \
 	| tar -C "${ENVTMPDIR}" -x
 
-${PTXDIST_SYSROOT_HOST}/bin/bareboxenv -s "${ENVTMPDIR}" "${IMAGEDIR}/barebox-environment"
+bareboxenv -s "${ENVTMPDIR}" "${IMAGEDIR}/barebox-environment"
 
-cp "${IMAGEDIR}/barebox-environment" "${PTXDIST_SETENV_BAREBOX_ENV}"
+# only copy the image if we are called by "test setenv"
+[ -n "${PTXDIST_SETENV_BAREBOX_ENV}" ] && cp "${IMAGEDIR}/barebox-environment" "${PTXDIST_SETENV_BAREBOX_ENV}"
 
 rm -rf "${ENVTMPDIR}"
diff --git a/tests/make_uboot_v2_env b/tests/make_uboot_v2_env
--- a/tests/make_uboot_v2_env
+++ b/tests/make_uboot_v2_env
@@ -4,6 +4,15 @@ set -e
 PTXDIST_SETENV_U_BOOT_V2_ENV="${1}"
 ENVTMPDIR="$(mktemp -d "${PTXDIST_TEMPDIR}/uboot_v2_env.XXXXXX")"
 
+# IMAGEDIR is not set if we are called from "ptxdist test" directly
+# since it comes from kwraper.
+[ -z "${IMAGEDIR}" ] && export IMAGEDIR=${PTXDIST_PLATFORMDIR}/images
+
+if [ ! -r ${PTXDIST_PLATFORMCONFIGDIR}/u-boot-env/config ]; then
+	echo "ERROR: missing valid ${PTXDIST_PLATFORMCONFIGDIR}/u-boot-env/config" >&2
+	exit 1
+fi
+
 tar -C "${PTXDIST_PLATFORMCONFIGDIR}/u-boot-env/" -c . \
 	--exclude .svn \
 	--exclude .pc \
@@ -12,8 +21,9 @@ tar -C "${PTXDIST_PLATFORMCONFIGDIR}/u-boot-env/" -c . \
 	--exclude "*/*~" \
 	| tar -C "${ENVTMPDIR}" -x
 
-${PTXDIST_SYSROOT_HOST}/bin/ubootenv -s "${ENVTMPDIR}" "${IMAGEDIR}/u-boot-v2-environment"
+ubootenv -s "${ENVTMPDIR}" "${IMAGEDIR}/u-boot-v2-environment"
 
-cp "${IMAGEDIR}/u-boot-v2-environment" "${PTXDIST_SETENV_U_BOOT_V2_ENV}"
+# only copy the image if we are called by "ptxdist test setenv"
+[ -n "${PTXDIST_SETENV_U_BOOT_V2_ENV}" ] && cp "${IMAGEDIR}/u-boot-v2-environment" "${PTXDIST_SETENV_U_BOOT_V2_ENV}"
 
 rm -rf "${ENVTMPDIR}"
