tests/setenv: print errors to user screen
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@10536 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/tests/setenv b/tests/setenv
--- a/tests/setenv
+++ b/tests/setenv
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ ! -e "${PTXDIST_BOARDSETUP}" ]; then
-	echo "Please run 'ptxdist boardsetup' first!"
+	echo "Please run 'ptxdist boardsetup' first!" >&2
 	exit 1
 fi
 
@@ -10,7 +10,7 @@ if [ ! -r "${CONFFILE}.in" ]; then
 	if [ -r "`dirname "${CONFFILE}"`/config.in" ]; then
 		CONFFILE="`dirname "${CONFFILE}"`/config"
 	else
-		echo "Config file for uboot environment is missing!"
+		echo "Config file for uboot environment is missing!" >&2
 		exit 1
 	fi
 fi
