* banner start script: adapt to common style
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@7918 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/generic/etc/init.d/banner b/generic/etc/init.d/banner
--- a/generic/etc/init.d/banner
+++ b/generic/etc/init.d/banner
@@ -2,21 +2,49 @@
 #
 # /etc/init.d/banner
 #
-# Copyright (C) 2004 Pengutronix
-# Robert Schwebel <r.schwebel@pengutronix.de>
-#
 
 FIGLET="/usr/sbin/figlet"
 FIGLET_FONTS="/usr/share/figlet"
+PATH=/sbin:/bin:/usr/bin
 
-echo
-echo "OSELAS(R)-@PROJECT@@PRJVERSION@ (@PTXDIST@-@VERSION@.@PATCHLEVEL@.@SUBLEVEL@@EXTRAVERSION@/@DATE@)"
-echo
-host=`/bin/hostname`
-if [ -n "@VENDOR@" ]; then
-	${FIGLET} -w 0 -f "${FIGLET_FONTS}/standard" "@VENDOR@"
-fi
-${FIGLET} -w 0 -f "${FIGLET_FONTS}/standard" "$host"
-echo
-echo
+test -f $FIGLET || { echo "$FIGLET not found" >&2 ; exit 1; }
+
+start_proc() {
+	echo
+	echo "OSELAS(R)-@PROJECT@@PRJVERSION@ (@PTXDIST@-@VERSION@.@PATCHLEVEL@.@SUBLEVEL@@EXTRAVERSION@/@DATE@)"
+	echo
+	host=`/bin/hostname`
+	if [ -n "@VENDOR@" ]; then
+		${FIGLET} -w 0 -f "${FIGLET_FONTS}/standard" "@VENDOR@"
+	fi
+	${FIGLET} -w 0 -f "${FIGLET_FONTS}/standard" "$host"
+	echo
+	echo
+}
+
+stop_proc() {
+}
+
+
+case "$1" in
+        start)
+        	start_proc
+		;;
+	stop)
+		stop_proc
+		;;
+        restart|force-reload)
+		start_proc
+                ;;
+        reload)
+                echo "Not supported" >&2
+                exit 1
+                ;;
+        *)
+                echo "Usage: $0 {start|stop|restart|force-reload}"
+                exit 1
+                ;;
+esac
+
+exit 0
 
