* apache2: add error handling to start file
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunks/ptxdist-trunk@6512 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/generic/etc/init.d/httpd b/generic/etc/init.d/httpd
--- a/generic/etc/init.d/httpd
+++ b/generic/etc/init.d/httpd
@@ -15,19 +15,31 @@ case "$1" in
     start)
             echo -n "${PREFIX}Starting $NAME: "
 	    /usr/sbin/apache2 -f @APACHECONFIG@ -k start
-            echo "Done"
+	    if [ $? = 0 ]; then
+                echo "Done"
+            else
+	        echo "Failed"
+            fi
         ;;
 
     stop)
             echo -n "${PREFIX}Stopping $NAME: "
 	    /usr/sbin/apache2 -f @APACHECONFIG@ -k stop
-            echo "Done"
+	    if [ $? = 0 ]; then
+                echo "Done"
+            else
+	        echo "Failed"
+            fi
         ;;
 
     reload)
             echo -n "${PREFIX}Restarting $NAME: "
 	    /usr/sbin/apache2 -f @APACHECONFIG@ -k restart
-            echo "Done"
+	    if [ $? = 0 ]; then
+                echo "Done"
+            else
+	        echo "Failed"
+            fi
         ;;
 
     *)
