bbu: added rc.d mimik
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunk@1339 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/etc/ratio-uno-2053-1/init.d/rcS b/etc/ratio-uno-2053-1/init.d/rcS
--- a/etc/ratio-uno-2053-1/init.d/rcS
+++ b/etc/ratio-uno-2053-1/init.d/rcS
@@ -64,3 +64,9 @@ chown system:users /home/system/boottime.log
 sync
 echo "done."
 
+echo -n "--- running rc.d services..."
+for i in /etc/init.d/* ; do {
+echo -n "[ $i ] ..." 
+$i || echo "*** FAILED ***" 
+}
+done;
