latest PII patches from rsc
git-svn-id: https://svn.pengutronix.de/svn/ptxdist/trunk@1541 33e552b5-05e3-0310-8538-816dae2090ed

diff --git a/etc/generic/init.d/rcS b/etc/generic/init.d/rcS
--- a/etc/generic/init.d/rcS
+++ b/etc/generic/init.d/rcS
@@ -19,11 +19,9 @@ echo -n "creating Network-Device lo..."
 ifconfig lo up 127.0.0.1
 echo "done."
 
-echo -n "running rc.d services..."
-for i in /etc/rc.d/* ; do {
-echo -n "[ $i ] ..." 
-$i || echo "*** FAILED ***" 
-}
-echo
+echo "running rc.d services..."
+for i in /etc/rc.d/* ; do
+	echo "[ $i ] ..." 
+	$i || echo "*** FAILED ***" 
 done;
 
